/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tikam.microservices.inventory_service.event;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class InventoryReservationFailedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6222243431616643374L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"InventoryReservationFailedEvent\",\"namespace\":\"com.tikam.microservices.inventory_service.event\",\"fields\":[{\"name\":\"orderNumber\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<InventoryReservationFailedEvent> ENCODER =
      new BinaryMessageEncoder<InventoryReservationFailedEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<InventoryReservationFailedEvent> DECODER =
      new BinaryMessageDecoder<InventoryReservationFailedEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<InventoryReservationFailedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<InventoryReservationFailedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<InventoryReservationFailedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<InventoryReservationFailedEvent>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this InventoryReservationFailedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a InventoryReservationFailedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a InventoryReservationFailedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static InventoryReservationFailedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence orderNumber;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public InventoryReservationFailedEvent() {}

  /**
   * All-args constructor.
   * @param orderNumber The new value for orderNumber
   */
  public InventoryReservationFailedEvent(java.lang.CharSequence orderNumber) {
    this.orderNumber = orderNumber;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orderNumber;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orderNumber = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'orderNumber' field.
   * @return The value of the 'orderNumber' field.
   */
  public java.lang.CharSequence getOrderNumber() {
    return orderNumber;
  }

  /**
   * Sets the value of the 'orderNumber' field.
   * @param value the value to set.
   */
  public void setOrderNumber(java.lang.CharSequence value) {
    this.orderNumber = value;
  }

  /**
   * Creates a new InventoryReservationFailedEvent RecordBuilder.
   * @return A new InventoryReservationFailedEvent RecordBuilder
   */
  public static com.tikam.microservices.inventory_service.event.InventoryReservationFailedEvent.Builder newBuilder() {
    return new com.tikam.microservices.inventory_service.event.InventoryReservationFailedEvent.Builder();
  }

  /**
   * Creates a new InventoryReservationFailedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new InventoryReservationFailedEvent RecordBuilder
   */
  public static com.tikam.microservices.inventory_service.event.InventoryReservationFailedEvent.Builder newBuilder(com.tikam.microservices.inventory_service.event.InventoryReservationFailedEvent.Builder other) {
    return new com.tikam.microservices.inventory_service.event.InventoryReservationFailedEvent.Builder(other);
  }

  /**
   * Creates a new InventoryReservationFailedEvent RecordBuilder by copying an existing InventoryReservationFailedEvent instance.
   * @param other The existing instance to copy.
   * @return A new InventoryReservationFailedEvent RecordBuilder
   */
  public static com.tikam.microservices.inventory_service.event.InventoryReservationFailedEvent.Builder newBuilder(com.tikam.microservices.inventory_service.event.InventoryReservationFailedEvent other) {
    return new com.tikam.microservices.inventory_service.event.InventoryReservationFailedEvent.Builder(other);
  }

  /**
   * RecordBuilder for InventoryReservationFailedEvent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<InventoryReservationFailedEvent>
    implements org.apache.avro.data.RecordBuilder<InventoryReservationFailedEvent> {

    private java.lang.CharSequence orderNumber;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.tikam.microservices.inventory_service.event.InventoryReservationFailedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderNumber)) {
        this.orderNumber = data().deepCopy(fields()[0].schema(), other.orderNumber);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing InventoryReservationFailedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.tikam.microservices.inventory_service.event.InventoryReservationFailedEvent other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.orderNumber)) {
        this.orderNumber = data().deepCopy(fields()[0].schema(), other.orderNumber);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'orderNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrderNumber() {
      return orderNumber;
    }

    /**
      * Sets the value of the 'orderNumber' field.
      * @param value The value of 'orderNumber'.
      * @return This builder.
      */
    public com.tikam.microservices.inventory_service.event.InventoryReservationFailedEvent.Builder setOrderNumber(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.orderNumber = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orderNumber' field has been set.
      * @return True if the 'orderNumber' field has been set, false otherwise.
      */
    public boolean hasOrderNumber() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orderNumber' field.
      * @return This builder.
      */
    public com.tikam.microservices.inventory_service.event.InventoryReservationFailedEvent.Builder clearOrderNumber() {
      orderNumber = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public InventoryReservationFailedEvent build() {
      try {
        InventoryReservationFailedEvent record = new InventoryReservationFailedEvent();
        record.orderNumber = fieldSetFlags()[0] ? this.orderNumber : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<InventoryReservationFailedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<InventoryReservationFailedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<InventoryReservationFailedEvent>
    READER$ = (org.apache.avro.io.DatumReader<InventoryReservationFailedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
