spring.application.name=notification-service
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=f1d82bc3b2c0ff
spring.mail.password=c05305bff48ba0

# kafka consumer properties
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notificationService
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.consumer.properties.schema.registry.url=http://127.0.0.1:8090
#spring.kafka.consumer.properties.avro.reader=true
spring.kafka.consumer.properties.specific.avro.reader=true

# mail properties
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=tikamsuvasiya333@gmail.com
#spring.mail.password=oiuq fjxo idcw vivu
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
server.port=9999
#spring.kafka.consumer.properties.spring.json.type.mapping=event:com.tikam.microservices.notification_service.events.order.Order


# loki url
loki.url=http://localhost:3100/loki/api/v1/push