version: '4'

services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: inventory_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:8.2.2
    container_name: redisson
    ports:
      - "6379:6379"